all: # This is build target `all`. This target will execute by default with `make` command.
	g++ main.cpp function1.cpp function2.cpp -o hello

compile: # This is build target `compile`. This target will execute if you pass: `make compile`.
	g++ main.cpp function3.cpp function4.cpp -o hello2
